#!/bin/bash

#Programa para gerência de atualizações!
#Todos podem editar esse programa, desde que o desenvolvedor original seja creditado

#1- update
#2- upgrade
#3- autoremove
#4- autoclean
#5- dist-upgrade
#6- install
#7- remove
#8- purge

blue="\033[1;34m"
white="\033[1;37m"
red="\033[1;31m"
yellow="\033[1;33m"
green="\033[1;32m"

ex=0
op=$1
ret=1

if [ $op != "1" ] && [ $op != "2" ] && [ $op != "3" ] && [ $op != "4" ] && [ $op != "5" ] && [ $op != "6" ] && [ $op != "7" ] && [ $op != "8" ]
	then
		exit
fi		

# [ $op != "1" ] && [ $op != "2" ] && [ $op != "3" ] && [ $op != "4" ] && [ $op != "5" ]

while [ $ret -eq 1 ] 
	do
		v=1
		clear
		if [ $# -eq 0 ]
			then
				echo -e "$red"
				echo -e "            ***************************************************"
				echo -e "            *$blue|@@@@@@@@|  |@@@@@@@@|      |@@@@@@@@@@@@@@@@@@@|$red*"
				echo -e "            *$blue|@@@@@@@@|  |@@@@@@@@|      |@@@@@@@@@@@@@@@@@@@|$red*"
				echo -e "            *$blue|@@@@@@@@|  |@@@@@@@@|      |@@@@@@|     |@@@@@@|$red*"
				echo -e "            *$blue|@@@@@@@@|  |@@@@@@@@|      |@@@@@@|     |@@@@@@|$red*"
				echo -e "            *$blue|@@@@@@@@|  |@@@@@@@@|      |@@@@@@@@@@@@@@@@@@@|$red*"
				echo -e "            *$blue|@@@@@@@@|  |@@@@@@@@|      |@@@@@@@@@@@@@@@@@@@|$red*"
				echo -e "            *$blue|@@@@@@@@|  |@@@@@@@@|      |@@@@@@|             $red*"
				echo -e "            *$blue|@@@@@@@@|  |@@@@@@@@|      |@@@@@@|             $red*"
				echo -e "            *$blue|@@@@@@@@@@@@@@@@@@@@|      |@@@@@@|             $red*"
				echo -e "            *$blue|@@@@@@@@@@@@@@@@@@@@|      |@@@@@@|             $red*"
				echo -e "            *                                                 *"
				echo -e "            *          $yellow Vitor Assis Camargo @ 2017  $red          *"
				echo -e " $red[0]$yellow SAIR   $red***************************************************"
				echo -e " $red[1]$white Atualizar lista de pacotes"
				echo -e " $red[2]$white Atualizar programas instalados"
				echo -e " $red[3]$white Desinstalar pacotes desnecessários"
				echo -e " $red[4]$white Apagar instaladores de pacotes"
				echo -e " $red[5]$white Atualizar distribuição"
				echo -e " $red[6]$white Instalar pacotes"
				echo -e " $red[7]$white Remover pacotes"
				echo -e " $red[8]$white Remover pacotes por completo (purge)"	
				echo 
				echo -ne "   $green#>$white "
		fi		
		if [ $# -eq 0 ]
			then
				read op;
		fi		
		if [ $op != "0" ] && [ $op != "1" ] && [ $op != "2" ] && [ $op != "3" ] && [ $op != "4" ] && [ $op != "5" ] && [ $op != "6" ]  && [ $op != "7" ] && [ $op != "8" ]
			then
				ret=1
			else
				ret=0
		fi			
		if [ $ret -eq 0 ]
			then
				case $op in
					"1")
						val="update"
						v=0
					;;
					"2")
						val="upgrade"
						v=0
					;;
					"3")
						val="autoremove"
						v=0
					;;
					"4")
						val="autoclean"
						v=0
					;;
					"5")
						val="dist-upgrade"
						v=0
					;;
					"6")
						val="install"
						v=0
					;;
					"7")
						val="remove"
						v=0
					;;
					"8")
						val="purge"
						v=0
					;;
					"0")
						exit
					;;
				esac
				if [ $op != "0" ] && [ $v -eq 0 ]
					then
						if [ $op = "6" ] || [ $op = "7" ] || [ $op = "8" ]
							then
								echo -ne " $red     pacote:$white "
								read pkt
								sudo apt $val $pkt
							else
								sudo apt $val
						fi
						if [ $? -eq 0 ]
							then
								str="Operação realizada com sucesso!!"
							else
								str="Falhou! Verifique sua rede"
						fi
						echo
						echo
						echo -ne "$green $str $blue"
						if [ $# -eq 1 ]
							then
								read
								clear
								exit
						fi
						echo -e " (Pressione <Enter> para retornar ao menu)$white"
						read
						ret=1
				fi
			fi
	done
clear
exit
